config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories

  root 'announcements#homepage'

  resources :announcements do
    collection do
      get 'homepage'
      post 'homepage'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new #guest user (not logged in)

    can :read, :all
    can :create, :all


    can :manage, Announcement do |announcement|
      announcement.user == user
  end
end     
end

app/models/announcement.rb
class Announcement < ApplicationRecord
	validates_presence_of :title, :description, :category, :price
	belongs_to :category
	belongs_to :user
	
	mount_uploaders :avatars, AvatarUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates_presence_of :name
  	has_many :announcements
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :homepage
  load_and_authorize_resource :except => [:homepage]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end
  
  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  def homepage
    @announcements = Announcement.order(:viewn)
    @announcements = @announcements.where(category: params[:category_id]) unless params[:category_id].blank?
    @announcements = @announcements.where("UPPER(description) like ?", "%#{params[:search_term].to_s.upcase}%") unless params[:search_term].blank?
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.user_id = current_user.id
    
    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:title, :description, :category_id, :price, :viewn, {avatars: []})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	protect_from_forgery with: :exception

	rescue_from CanCan::AccessDenied do |exception|
		respond_to do |format|
			format.json { head :forbidden, content_type: 'text/html' }
			format.html { redirect_to main_app.root_url, notice: exception.message }
			format.js   { head :forbidden, content_type: 'text/html' }
		end
	end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:phone, :adress ,:email])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :adress ,:email, bank_attributes: [:bank_name, :bank_account]])
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
  end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/announcements/_form.html.erb
<%= form_with(model: announcement, local: true) do |form| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% announcement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Categoria %>
    <%= form.select :category_id, Category.all.collect {|category| [category.name, category.id]}, {}, {class: 'form-control'} %>
  </div>

  <h5>
    <strong><%= link_to 'Incluir Categoria', new_category_path %></strong>
  </h5>

  <div class="field">
    <%= form.label :Título %>
    <%= form.text_field :title, id: :announcement_title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :Descrição %>
    <%= form.text_field :description, id: :announcement_description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :Preço %>
    <%= form.text_field :price, id: :announcement_price, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :Imagens %>
    <%= form.file_field :avatars, multiple: true %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/homepage.html.erb
<div class="row">
  <div class="col-md-8">
    <% @announcements.all.each do |announcement| %>
    <ul class="list-group">
      <li class="list-group-item">
        <h2><a href="../announcements/<%= announcement.id %>"><%= announcement.title %></a></h2>
      </li>
      <li class="list-group-item">
        <% announcement.avatars.each do |avatar| %>
        <%= image_tag (avatar.thumb.url) unless avatar.file.nil? %>
        <%break%>
        <% end %>
      </li>
      <li class="list-group-item">
        <h3><%= announcement.description %></h3>
      </li>
      <li class="list-group-item">
        <h3>Category: <%= announcement.category.name %></h3>
      </li>
      <li class="list-group-item">
        <p><%= announcement.price %></p>
      </li>
      <li class="list-group-item">
        <strong>Author: <%= announcement.user.email %></strong>
      </li>


    </ul>
    <% end %>
  </div>
  <div class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Categories</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% Category.all.each do |category| %>
          <li>
            <%= link_to category.name, homepage_announcements_path(category_id: category.id) %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Search</h3>
      </div>
      <div class="panel-body">
        <%= form_tag("/announcements/homepage", method: "post") do %>
        <%= text_field_tag(:search_term) %>
        <%= submit_tag("Search") %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Announcements</h1>

<table>


  <tbody>
  <table class="table">
    <tr>
      <th>Title</th>
      <th>Picture</th>
      <th>Description</th>
      <th>Price</th>
      <th>Views number</th>
    </tr>

    <% Announcement.all.each do |announcement| %>
      <% if announcement.user == current_user %>


      <tr>
        <td><%= announcement.title %></td>
        <td>
          <% announcement.avatars.each do |avatar| %>
            <%= image_tag (avatar.thumb.url) unless avatar.file.nil? %>
            <% break %>
          <% end %></td>
        <td><%= announcement.description %></td>
        <td><%= announcement.price %></td>
        <td><%= announcement.viewn %></td>
        <td><%= link_to 'Ver', announcement , class: 'btn btn-info'%></td>
        <td><%= link_to 'Editar', edit_announcement_path(announcement),  class: 'btn btn-info' %></td>
        <td><%= link_to 'Excluir', announcement, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-info'  %></td>
      </tr>

      <%end%>
    <% end %>
  </table>
  </tbody>
</table>

<br>

<%= link_to '', new_announcement_path, class: 'btn btn-info' %>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="list-group">

	<li class="list-group-item">
		<p>
			<strong>Title:</strong>
			<%= @announcement.title %>
		</p>
	</li>

	<li class="list-group-item">
		<% @announcement.avatars.each do |avatar| %>
			<%= image_tag (avatar.url) unless avatar.file.nil? %>
		<% end %>
	</li>

	<li class="list-group-item">
		<p>
			<strong>Anunciante:</strong>
			<%= @announcement.user.name %>
		</p>

	</li>

	<li class="list-group-item">
		<p>
			<strong>Description:</strong>
			<%= @announcement.description %>
		</p>
	</li>

	<li class="list-group-item">
		<p>
			<strong>Price:</strong>
			<%= @announcement.price %>
		</p>
	</li>

	<li class="list-group-item">
		<p>
			<strong>Viewn:</strong>
			<%= @announcement.viewn %>
		</p>
	</li>

</ul>

<p>
	Talvez você esteja buscando por...
</p>

<% Announcement.all.each do |an| %>
<% if @announcement.category ==  an.category && @announcement.id != an.id%>
<ul class="ulRelacionada">

	<h2></h2>

	<li class="listaRelacionada">
		<% an.avatars.each do |avatar| %>
		<%= image_tag (avatar.thumb.url) unless avatar.file.nil? %>
		<% end %>
	</li>
	<li class="listaRelacionada">
		<p>
			<strong>Title:</strong>
			<a href="../announcements/<%= an.id %>"><%= an.title %></a>
		</p>
	</li>
	<li class="listaRelacionada">
		<p>
			<strong>Anunciante:</strong>
			<%= an.user.id %>
		</p>
	</li>
</ul>

<%end%>
<%end%>

<%= link_to '', edit_announcement_path(@announcement), class: 'btn btn-info' %>
<%= link_to '', announcements_path, class: 'btn btn-info glyphicon' %>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Emporio Vendas</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <%= link_to 'Novo anúncio', new_announcement_path %>
        <%= link_to 'Nova categoria', new_category_path %>
        <% if user_signed_in? %>
        <%= link_to 'Meus anúncios', announcements_path %>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmporioVendas</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

    <%= stylesheet_link_tag %>   
    <!-- 'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
    <%= javascript_include_tag %>
    <!-- 'application', 'data-turbolinks-track': 'reload' %> -->
</head>

<body>
  <%= render '/layouts/menu' %>
  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>